# -*- coding: utf-8 -*-
"""
Created on Fri Nov  8 11:39:28 2024

@author: dthtr

#source: borrow and adapted from ClarityNLP


"""






stopwords = ['a', 'about', 'above', 'after', 'again', 'against', 'all', 'almost', 
             'already', 'along','another', 'around', 'also', 'although', 'am', 
             'among', 'an', 'and', 'another', 'any', 'are', 'as', 'at', 
             'be', 'because', 'before', 'behind', 'below', 'beside', 'besides', 
             'between', 'beyond', 'both', 'but', 'by', 'can', 'co', 'corp',
             'd', 'do', 'during', 
             'each', 'elsewhere', 'etc', 'even', 'ever', 'ex', 
             'few', 'for', 'from', 'further', 'furthermore', 
             'had', 'have', 'he', 'hence', 'her', 'here', 'hers', 'herself', 
             'him', 'himself', 'his', 'how', 'however',
             'i', 'if', 'in',  'spite','into', 'it', 'its', 'itself', 
             'just',
             'll', 
             'm', 'may', 'me', 'meanwhile', 'might', 'moreover', 'my', 'myself', 
             'neither', 'no', 'nor', 'not', 'now', 
             'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 
             'our', 'ours', 'ourselves', 'out', 'over', 'overall', 'own', 
             're', 
             's', 'same', 'several', 'shall','she', 'so', 'some', 'such', 
             't', 'than', 'that', 'the', 'their', 'theirs', 'them', 'themselves', 
             'then', 'there', 'therefore', 'these', 'they', 
             'this', 'those', 'through', 'to', 'too', 
             'under', 'until', 
             've', 'very', 'via', 
             'we', 'what', 'when', 'where', 'which', 'while', 
             'who', 'whom', 'why', 'will', 'with', 
             'y', 'yet', 'you', 'your', 'yours', 'yourself', 'yourselves']         












#no need to check inflection that is same with baseform
#because it would already be indexed

#irregular verb inflection which is different from the base form
irr_inflection_len3 = {
 'was': 'be',
 'bet': 'bet',
 'bit': 'bite',
 'dug': 'dig',
 'did': 'do',
 'ate': 'eat',
 'fed': 'feed',
 'got': 'get',
 'had': 'have',
 'hid': 'hide',
 'led': 'lead',
 'lit': 'light',
 'met': 'meet',
 'rid': 'rid',
 'ran': 'run',
 'saw': 'see',
 'sat': 'sit',
 'won': 'win'
 }


#all the inflection that does not ends in ed


irr_inflection = {
     'alit': 'alight',
     'arose': 'arise',
     'arisen': 'arise',
     'awoke': 'awake',
     'awoken': 'awake',
     'babysat': 'babysit',
     'backlit': 'backlight',
     'backslid': 'backslide',
     'backslidden': 'backslide',
     'been': 'be',
     'bore': 'bear',
     'borne': 'bear',
     'born': 'bear',
     'beat': 'beat',
     'beaten': 'beat',
     'became': 'become',
     'bedid': 'bedo',
     'bedone': 'bedo',
     'bedrew': 'bedraw',
     'bedrawn': 'bedraw',
     'bedreamt': 'bedream',
     'bedrove': 'bedrive',
     'bedriven': 'bedrive',
     'bedwelt': 'bedwell',
     'befell': 'befall',
     'befallen': 'befall',
     'befought': 'befight',
     'began': 'begin',
     'begun': 'begin',
     'beheard': 'behear',
     'beheld': 'behold',
     'bekent': 'beken',
     'beknit': 'beknit',
     'belaid': 'belay',
     'beleapt': 'beleap',
     'beleft': 'beleave',
     'bent': 'bend',
     'bequoth': 'bequeath',
     'bequod': 'bequeath',
     'bequethen': 'bequeath',
     'bereft': 'bereave',
     'besought': 'beseek',
     'beset': 'beset',
     'bespoke': 'bespeak',
     'bespoken': 'bespeak',
     'bestrewn': 'bestrew',
     'bestrode': 'bestride',
     'bestridden': 'bestride',
     'betook': 'betake',
     'betaken': 'betake',
     'betow': 'betee',
     'betown': 'betee',
     'bode': 'bide',
     'bidden': 'bide',
     'bound': 'bind',
     'bitten': 'bite',
     'blew': 'blow',
     'blown': 'blow',
     'broke': 'break',
     'broken': 'break',
     'brought': 'bring',
     'broadcast': 'broadcast',
     'browbeat': 'browbeat',
     'browbeaten': 'browbeat',
     'built': 'build',
     'burnt': 'burn',
     'burst': 'burst',
     'bought': 'buy',
     'could': 'can',
     'cast': 'cast',
     'caught': 'catch',
     'chid': 'chide',
     'chidden': 'chide',
     'chose': 'choose',
     'chosen': 'choose',
     'clad': 'clothe',
     'clearcut': 'clearcut',
     'cleft': 'cleave',
     'clove': 'cleave',
     'cloven': 'cleave',
     'clung': 'cling',
     'came': 'come',
     'comen': 'come',
     'cost': 'cost',
     'cowrote': 'cowrite',
     'cowritten': 'cowrite',
     'crept': 'creep',
     'crosscut': 'crosscut',
     'crew': 'crow',
     'dealt': 'deal',
     'dove': 'dive',
     'done': 'do',
     'dought': 'dow',
     'downcast': 'downcast',
     'downdrew': 'downdraw',
     'downdrawn': 'downdraw',
     'drew': 'draw',
     'drawn': 'draw',
     'dreamt': 'dream',
     'drank': 'drink',
     'drunk': 'drink',
     'drove': 'drive',
     'driven': 'drive',
     'dwelt': 'dwell',
     'earnt': 'earn',
     'eaten': 'eat',
     'fell': 'fall',
     'fallen': 'fall',
     'felt': 'feel',
     'fought': 'fight',
     'found': 'find',
     'flung': 'fling',
     'flew': 'fly',
     'flown': 'fly',
     'forbore': 'forbear',
     'forborne': 'forbear',
     'forborn': 'forbear',
     'forbid': 'forbid',
     'forbade': 'forbid',
     'forbad': 'forbid',
     'forbidden': 'forbid',
     'forecast': 'forecast',
     'forefelt': 'forefeel',
     'forewent': 'forego',
     'foregone': 'forego',
     'foreheard': 'forehear',
     'forekent': 'foreken',
     'foreknew': 'foreknow',
     'foreknown': 'foreknow',
     'foresaw': 'foresee',
     'foreseen': 'foresee',
     'foreshown': 'foreshow',
     'foretold': 'foretell',
     'forgot': 'forget',
     'forgotten': 'forget',
     'forgave': 'forgive',
     'forgiven': 'forgive',
     'forwent': 'forgo',
     'forgone': 'forgo',
     'forsook': 'forsake',
     'forsaken': 'forsake',
     'forstood': 'forstand',
     'forswore': 'forswear',
     'forsworn': 'forswear',
     'fortow': 'fortee',
     'fortown': 'fortee',
     'forthcame': 'forthcome',
     'forthcome': 'forthcome',
     'forthleapt': 'forthleap',
     'forthtold': 'forthtell',
     'froze': 'freeze',
     'frozen': 'freeze',
     'frate': 'fret',
     'fretten': 'fret',
     'frostbit': 'frostbite',
     'frostbitten': 'frostbite',
     'gotten': 'get',
     'ghostwrote': 'ghostwrite',
     'ghostwritten': 'ghostwrite',
     'gilt': 'gild',
     'gave': 'give',
     'given': 'give',
     'gone': 'go',
     'green-lit': 'green-light',
     'ground': 'grind',
     'grew': 'grow',
     'grown': 'grow',
     'hamstrung': 'hamstring',
    'handset': 'handset',
    'handsewn': 'handsew',
    'handsprang': 'handspring',
    'handsprung': 'handspring',
    'handwrote': 'handwrite',
    'handwritten': 'handwrite',
    'hung': 'hang',
    'heard': 'hear',
    'hewn': 'hew',
    'hidden': 'hide',
    'hoist': 'hoist',
    'held': 'hold',
    'housesat': 'housesit',
    'inheld': 'inhold',
    'inlaid': 'inlay',
    'inset': 'inset',
    'intook': 'intake',
    'intaken': 'intake',
    'intercut': 'intercut',
    'interlaid': 'interlay',
    'interwove': 'interweave',
    'interwoven': 'interweave',
    'kept': 'keep',
    'kent': 'ken',
    'knelt': 'kneel',
    'knit': 'knit',
    'knew': 'know',
    'known': 'know',
    'laden': 'lade',
    'laid': 'lay',
    'leant': 'lean',
    'leapt': 'leap',
    'learnt': 'learn',
    'left': 'leave',
    'lent': 'lend',
    'lain': 'lie',
    'lipread': 'lipread',
    'lost': 'lose',
    'made': 'make',
    'might': 'may',
    'meant': 'mean',
    'molten': 'melt',
    'misbecame': 'misbecome',
    'misbecome': 'misbecome',
    'misbegot': 'misbeget',
    'misbegotten': 'misbeget',
    'miscast': 'miscast',
    'mischose': 'mischoose',
    'mischosen': 'mischoose',
    'misdealt': 'misdeal',
    'misdid': 'misdo',
    'misdone': 'misdo',
    'misfit': 'misfit',
    'misgave': 'misgive',
    'misgiven': 'misgive',
    'misheard': 'mishear',
    'mishit': 'mishit',
    'misheld': 'mishold',
    'miskept': 'miskeep',
    'miskent': 'misken',
    'misknew': 'misknow',
    'misknown': 'misknow',
    'mislaid': 'mislay',
    'mislearnt': 'mislearn',
    'misread': 'misread',
    'missaid': 'missay',
    'missaw': 'missee',
    'misseen': 'missee',
    'missent': 'missend',
    'misset': 'misset',
    'misshot': 'misshoot',
    'misspoke': 'misspeak',
    'misspoken': 'misspeak',
    'misspelt': 'misspell',
    'misspent': 'misspend',
    'mistook': 'mistake',
    'mistaken': 'mistake',
    'mistold': 'mistell',
    'misthrew': 'misthrow',
    'misthrown': 'misthrow',
    'misunderstood': 'misunderstand',
    'miswrote': 'miswrite',
    'miswritten': 'miswrite',
    'mown': 'mow',
    'offset': 'offset',
    'onlaid': 'onlay',
    'outbid': 'outbid',
    'outbidden': 'outbid',
    'outbroke': 'outbreak',
    'outbroken': 'outbreak',
    'outdid': 'outdo',
    'outdone': 'outdo',
    'outdrew': 'outdraw',
    'outdrawn': 'outdraw',
    'outdrank': 'outdrink',
    'outdrunk': 'outdrink',
    'outdwelt': 'outdwell',
    'outate': 'outeat',
    'outeaten': 'outeat',
    'outfell': 'outfall',
    'outfallen': 'outfall',
    'outfought': 'outfight',
    'outflew': 'outfly',
    'outflown': 'outfly',
    'outgrew': 'outgrow',
    'outgrown': 'outgrow',
    'outheard': 'outhear',
    'outkent': 'outken',
    'outlaid': 'outlay',
    'outleapt': 'outleap',
    'output': 'output',
    'outrode': 'outride',
    'outridden': 'outride',
    'outran': 'outrun',
    'outrun': 'outrun',
    'outsold': 'outsell',
    'outshone': 'outshine',
    'outspent': 'outspend',
    'outspun': 'outspin',
    'outspread': 'outspread',
    'outstrode': 'outstride',
    'outstridden': 'outstride',
    'outstrove': 'outstrive',
    'outstriven': 'outstrive',
    'outswore': 'outswear',
    'outsworn': 'outswear',
    'outswam': 'outswim',
    'outswum': 'outswim',
    'outthought': 'outthink',
    'outthrew': 'outthrow',
    'outthrown': 'outthrow',
    'outwore': 'outwear',
    'outworn': 'outwear',
    'overbore': 'overbear',
    'overborne': 'overbear',
    'overborn': 'overbear',
    'overbeat': 'overbeat',
    'overbeaten': 'overbeat',
    'overbent': 'overbend',
    'overbid': 'overbid',
    'overblew': 'overblow',
    'overblown': 'overblow',
    'overbuilt': 'overbuild',
    'overbought': 'overbuy',
    'overcast': 'overcast',
    'overclad': 'overclothe',
    'overcame': 'overcome',
    'overcome': 'overcome',
    'overcomen': 'overcome',
    'overdid': 'overdo',
    'overdone': 'overdo',
    'overdrew': 'overdraw',
    'overdrawn': 'overdraw',
    'overdrank': 'overdrink',
    'overdrunk': 'overdrink',
    'overdrove': 'overdrive',
    'overdriven': 'overdrive',
    'overate': 'overeat',
    'overeaten': 'overeat',
    'overflew': 'overfly',
    'overflown': 'overfly',
    'overgave': 'overgive',
    'overgiven': 'overgive',
    'overgrew': 'overgrow',
    'overgrown': 'overgrow',
    'overhung': 'overhang',
    'overheard': 'overhear',
    'overhit': 'overhit',
    'overkept': 'overkeep',
    'overladen': 'overlade',
    'overlaid': 'overlay',
    'overleapt': 'overleap',
    'overlearnt': 'overlearn',
    'overleft': 'overleave',
    'overlay': 'overlie',
    'overlain': 'overlie',
    'overpaid': 'overpay',
    'overrode': 'override',
    'overridden': 'override',
    'overran': 'overrun',
    'overrun': 'overrun',
    'oversaw': 'oversee',
    'overseen': 'oversee',
    'oversold': 'oversell',
    'overset': 'overset',
    'oversewn': 'oversew',
    'overshook': 'overshake',
    'overshaken': 'overshake',
    'overshone': 'overshine',
    'overshot': 'overshoot',
    'overshrank': 'overshrink',
    'overshrunk': 'overshrink',
    'overshrunken': 'overshrink',
    'overslept': 'oversleep',
    'overslid': 'overslide',
    'overslidden': 'overslide',
    'overspent': 'overspend',
    'overspilt': 'overspill',
    'overspread': 'overspread',
    'overstood': 'overstand',
    'overstrewn': 'overstrew',
    'overstrode': 'overstride',
    'overstridden': 'overstride',
    'overstruck': 'overstrike',
    'overstricken': 'overstrike',
    'overstrung': 'overstring',
    'overstrove': 'overstrive',
    'overstriven': 'overstrive',
    'overswang': 'overswing',
    'overswung': 'overswing',
    'overtook': 'overtake',
    'overtaken': 'overtake',
    'overthrew': 'overthrow',
    'overthrown': 'overthrow',
    'overwore': 'overwear',
    'overworn': 'overwear',
    'overwet': 'overwet',
    'overwrought': 'overwork',
    'overwrote': 'overwrite',
    'overwritten': 'overwrite',
    'partook': 'partake',
    'partaken': 'partake',
    'paid': 'pay',
    'pent': 'pen',
    'plead': 'plead',
    'podcast': 'podcast',
    'precast': 'precast',
    'prepaid': 'prepay',
    'preset': 'preset',
    'proofread': 'proofread',
    'proven': 'prove',
    'quick-froze': 'quick-freeze',
    'quick-frozen': 'quick-freeze',
    'quit': 'quit',
    'read': 'read',
    'rebid': 'rebid',
    'rebroke': 'rebreak',
    'rebroken': 'rebreak',
    'rebuilt': 'rebuild',
    'recast': 'recast',
    'recut': 'recut',
    'redealt': 'redeal',
    'redid': 'redo',
    'redone': 'redo',
    'redrew': 'redraw',
    'redrawn': 'redraw',
    'refound': 'refind',
    'refroze': 'refreeze',
    'refrozen': 'refreeze',
    'regrew': 'regrow',
    'regrown': 'regrow',
    'reheard': 'rehear',
    'relearnt': 'relearn',
    'relit': 'relight',
    'remade': 'remake',
    'rent': 'rend',
    'repaid': 'repay',
    'reproven': 'reprove',
    'reread': 'reread',
    'reran': 'rerun',
    'rerun': 'rerun',
    'resold': 'resell',
    'resent': 'resend',
    'reset': 'reset',
    'reshod': 'reshoe',
    'reshodden': 'reshoe',
    'reshot': 'reshoot',
    'reshown': 'reshow',
    'reshut': 'reshut',
    'resang': 'resing',
    'resung': 'resing',
    'resat': 'resit',
    'retook': 'retake',
    'retaken': 'retake',
    'retold': 'retell',
    'rethought': 'rethink',
    'retrod': 'retread',
    'retrodden': 'retread',
    'rewound': 'rewind',
    'rewrote': 'rewrite',
    'rewritten': 'rewrite',
    'ridden': 'ride',
    'rode': 'ride',
    'rang': 'ring',
    'rung': 'ring',
    'rose': 'rise',
    'risen': 'rise',
    'rove': 'rive',
    'riven': 'rive',
    'sawn': 'saw',
    'said': 'say',
    'seen': 'see',
    'sought': 'seek',
    'sold': 'sell',
    'sent': 'send',
    'sewn': 'sew',
    'shook': 'shake',
    'shaken': 'shake',
    'should': 'shall',
    'shaven': 'shave',
    'shore': 'shear',
    'shorn': 'shear',
    'shone': 'shine',
    'shit': 'shite',
    'shat': 'shite',
    'shitten': 'shite',
    'shod': 'shoe',
    'shodden': 'shoe',
    'shot': 'shoot',
    'shown': 'show',
    'shrank': 'shrink',
    'shrunk': 'shrink',
    'shrunken': 'shrink',
    'shut': 'shut',
    'sight-read': 'sight-read',
    'sightsaw': 'sightsee',
    'sightseen': 'sightsee',
    'simulcast': 'simulcast',
    'sang': 'sing',
    'sung': 'sing',
    'sank': 'sink',
    'sunk': 'sink',
    'sunken': 'sink',
    'slew': 'slay',
    'slain': 'slay',
    'slept': 'sleep',
    'slid': 'slide',
    'slidden': 'slide',
    'slung': 'sling',
    'slunk': 'slink',
    'slank': 'slink',
    'slit': 'slit',
    'slitten': 'slit',
    'smelt': 'smell',
    'smote': 'smite',
    'smitten': 'smite',
    'snuck': 'sneak',
    'soothsaid': 'soothsay',
    'sown': 'sow',
    'spoke': 'speak',
    'spoken': 'speak',
    'spelt': 'spell',
    'spent': 'spend',
    'spilt': 'spill',
    'spun': 'spin',
    'spat': 'spit',
    'spit': 'spit',
    'split': 'split',
    'spoilt': 'spoil',
    'spread': 'spread',
    'sprang': 'spring',
    'sprung': 'spring',
    'stood': 'stand',
    'stove': 'stave',
    'stole': 'steal',
    'stolen': 'steal',
    'stuck': 'stick',
    'stung': 'sting',
    'stank': 'stink',
    'stunk': 'stink',
    'strewn': 'strew',
    'strode': 'stride',
    'stridden': 'stride',
    'struck': 'strike',
    'stricken': 'strike',
    'strung': 'string',
    'stript': 'strip',
    'strove': 'strive',
    'striven': 'strive',
    'sublet': 'sublet',
    'sunburnt': 'sunburn',
    'swore': 'swear',
    'sworn': 'swear',
    'sweat': 'sweat',
    'swept': 'sweep',
    'swollen': 'swell',
    'swam': 'swim',
    'swum': 'swim',
    'swang': 'swing',
    'swung': 'swing',
    'took': 'take',
    'taken': 'take',
    'taught': 'teach',
    'tore': 'tear',
    'torn': 'tear',
    'telecast': 'telecast',
    'told': 'tell',
    'test-drove': 'test-drive',
    'test-driven': 'test-drive',
    'test-flew': 'test-fly',
    'test-flown': 'test-fly',
    'thought': 'think',
    'throve': 'thrive',
    'thriven': 'thrive',
    'threw': 'throw',
    'thrown': 'throw',
    'thrust': 'thrust',
    'trod': 'tread',
    'trodden': 'tread',
    'typecast': 'typecast',
    'unbent': 'unbend',
    'unbound': 'unbind',
    'unclad': 'unclothe',
    'underbore': 'underbear',
    'underborne': 'underbear',
    'underborn': 'underbear',
    'underbet': 'underbet',
    'underbid': 'underbid',
    'underbound': 'underbind',
    'underbuilt': 'underbuild',
    'underbought': 'underbuy',
    'undercast': 'undercast',
    'underclad': 'underclothe',
    'undercut': 'undercut',
    'underdug': 'underdig',
    'underdid': 'underdo',
    'underdone': 'underdo',
    'underdrew': 'underdraw',
    'underdrawn': 'underdraw',
    'underate': 'undereat',
    'undereaten': 'undereat',
    'underwent': 'undergo',
    'undergone': 'undergo',
    'undergrew': 'undergrow',
    'undergrown': 'undergrow',
    'underhung': 'underhang',
    'underhit': 'underhit',
    'underkept': 'underkeep',
    'underlaid': 'underlay',
    'underlay': 'underlie',
    'underlain': 'underlie',
    'underpaid': 'underpay',
    'underran': 'underrun',
    'underrun': 'underrun',
    'undersaw': 'undersee',
    'underseen': 'undersee',
    'undersold': 'undersell',
    'undershot': 'undershoot',
    'underslept': 'undersleep',
    'underspread': 'underspread',
    'understood': 'understand',
    'undertook': 'undertake',
    'undertaken': 'undertake',
    'underthrew': 'underthrow',
    'underthrown': 'underthrow',
    'underwrote': 'underwrite',
    'underwritten': 'underwrite',
    'undid': 'undo',
    'undone': 'undo',
    'unfroze': 'unfreeze',
    'unfrozen': 'unfreeze',
    'unheard': 'unhear',
    'unlaid': 'unlay',
    'unlearnt': 'unlearn',
    'unmade': 'unmake',
    'unwound': 'unwind',
    'upcast': 'upcast',
    'updrew': 'updraw',
    'updrawn': 'updraw',
    'upgrew': 'upgrow',
    'upgrown': 'upgrow',
    'uphung': 'uphang',
    'uphove': 'upheave',
    'upheld': 'uphold',
    'uprose': 'uprise',
    'uprisen': 'uprise',
    'upsold': 'upsell',
    'upset': 'upset',
    'upstood': 'upstand',
    'upswept': 'upsweep',
    'upswollen': 'upswell',
    'uptore': 'uptear',
    'uptorn': 'uptear',
    'upthrew': 'upthrow',
    'upthrown': 'upthrow',
    'woke': 'wake',
    'woken': 'wake',
    'waylaid': 'waylay',
    'wore': 'wear',
    'worn': 'wear',
    'wove': 'weave',
    'woven': 'weave',
    'webcast': 'webcast',
    'wept': 'weep',
    'would': 'will',
    'wound': 'wind',
    'withdrew': 'withdraw',
    'withdrawn': 'withdraw',
    'withheld': 'withhold',
    'withstood': 'withstand',
    'wrought': 'wreak',
    'wrang': 'wring',
    'wrung': 'wring',
    'wrote': 'write',
    'written': 'write'
    }
    

irr_plural = {
    'people': 'person',
    'feet' : 'foot',
    'teeth': 'tooth',
    'goose': 'geese',
    'children': 'child',
    'mice': 'mouse',
    'criteria': 'criterion',
    'phenomena': 'phenomenon',
    'men': 'man',
    'women': 'women',
    'fungi': 'fungus',
    'nuclei':'nucleus',
    'cacti' : 'cactus',
    'alumni': 'alumnus',
    'oxen':	'ox',
    'data':	'datum',
    'memoranda': 'memorandum',	
    'bacteria' : 'bacterium',	
    'strata' : 'stratum',
    'curricula':'curriculum'
    }


